server:
  port: 7901
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: application-consumer

hystrix.command.default.execution.timeout.enabled: false